FROM adoptopenjdk:11-jdk-hotspot
RUN apt-get update -qqy  && apt-get -qqy install file binutils libjemalloc-dev graphviz  openjdk-11-dbg \
      --no-install-recommends \
     && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

