FROM eclipse-temurin:17-jdk
RUN apt-get update -qqy  && apt-get -qqy install file binutils libjemalloc-dev graphviz \
      --no-install-recommends \
     && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

